version: 'latest'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: backend
    restart: always

    volumes:
      - static:/app/static
      - media:/app/media

    expose:
      - '8080'

    depends_on:
      - "db"
      - "nginx"


  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile

    container_name: nginx
    restart: always

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static
      - media:/app/media

    ports:
      - '80:80'

  db:
    image: postgres
    container_name: db
    restart: 'always'

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    volumes:

      - postgres_data:/var/lib/postgresql/data/

    ports:
      - '5432:5432'

volumes:
  static:
  media:
  postgres_data:
